export const seasonData = [
  {
    season: 1,
    name: "Indigo League",
    episodes: [
      "Pokémon, I Choose You!",
      "Pokémon Emergency!",
      "Ash Catches a Pokémon",
      "Challenge of the Samurai",
      "Showdown in Pewter City",
      "Clefairy and the Moon Stone",
      "The Water Flowers of Cerulean City",
      "The Path to the Pokémon League",
      "The School of Hard Knocks",
      "Bulbasaur and the Hidden Village",
      "Charmander – The Stray Pokémon",
      "Here Comes the Squirtle Squad",
      "Mystery at the Lighthouse",
      "Electric Shock Showdown",
      "Battle Aboard the St. Anne",
      "Pokémon Shipwreck",
      "Island of the Giant Pokémon",
      "Beauty and the Beach",
      "Tentacool & Tentacruel",
      "The Ghost of Maiden's Peak",
      "Bye Bye Butterfree",
      "Abra and the Psychic Showdown",
      "The Tower of Terror",
      "Haunter Versus Kadabra",
      "Primeape Goes Bananas",
      "Pokémon Scent-sation!",
      "Hypno's Naptime",
      "Pokémon Fashion Flash",
      "The Punchy Pokémon",
      "Sparks Fly for Magnemite",
      "Dig Those Diglett!",
      "The Ninja-Poké Showdown",
      "The Flame Pokémon-athon!",
      "The Kangaskhan Kid",
      "The Bridge Bike Gang",
      "Ditto's Mysterious Mansion",
      "Pikachu's Goodbye",
      "The Problem with Paras",
      "The Song of Jigglypuff",
      "Attack of the Prehistoric Pokémon",
      "A Chansey Operation",
      "Holy Matrimony!",
      "Danger: Pokémon at Work",
      "A Snow Day at the Pokémon Center",
      "The Poké-Yawn",
      "The Little Big Horn",
      "The Misty Mermaid",
      "Clefairy Tales",
      "The Battle of the Badge",
      "It's Mr. Mime Time!",
      "The Psychic Sidekicks",
      "The Breeding Center and the Pokémon Egg",
      "The Wacky Watcher!",
      "The Mandarin Island Miss Match",
      "Wherefore Art Thou, Pokémon?",
      "Get Along, Little Pokémon",
      "The Mystery Menace",
      "Misty Meets Her Match",
      "Bound for Trouble",
      "Charizard Chills",
      "The Pokémon Water War",
      "Pokémon Food Fight!",
      "Pokémon Double Trouble",
      "The Stun Spore Detour",
      "Hello, Pummelo!",
      "Enter the Dragonite",
      "The Rivalry Revival",
      "The Underground Round-Up",
      "A Tent Situation",
      "The Lighthouse Saga",
      "The Joy of Pokémon",
      "Snack Attack",
      "A Shipful of Shivers",
      "Meowth Rules!",
      "Tracey Gets Bugged",
      "A Way Off Day Off",
      "The Case of the K-9 Caper!",
      "Who Gets To Keep Togepi?"
    ]
  },
  {
    season: 2,
    name: "Adventures in the Orange Islands",
    episodes: [
      "Pallet Party Panic",
      "A Scare in the Air",
      "Poké Ball Peril",
      "The Lost Lapras",
      "Fit to Be Tide",
      "Pikachu Re-Volts",
      "The Crystal Onix",
      "In the Pink",
      "Shell Shock!",
      "Stage Fight!",
      "Bye Bye Psyduck",
      "The Joy of Pokémon",
      "Navel Maneuvers",
      "Snack Attack",
      "A Shipful of Shivers",
      "Meowth Rules!",
      "Tracey Gets Bugged",
      "A Way Off Day Off",
      "The Mandarin Island Miss Match",
      "Wherefore Art Thou, Pokémon?",
      "Get Along, Little Pokémon",
      "The Mystery Menace",
      "Misty Meets Her Match",
      "Bound for Trouble",
      "Charizard Chills",
      "The Pokémon Water War",
      "Pokémon Food Fight!",
      "Pokémon Double Trouble",
      "The Wacky Watcher!",
      "The Stun Spore Detour",
      "Hello, Pummelo!",
      "Enter the Dragonite",
      "The Rivalry Revival",
      "A Tent Situation",
      "The Underground Round-Up",
      "Hello, Pummelo!"
    ]
  },
  {
    season: 3,
    name: "The Johto Journeys",
    episodes: [
      "Don't Touch That 'dile",
      "The Double Trouble Header",
      "A Sappy Ending",
      "Roll On, Pokémon!",
      "Illusion Confusion!",
      "Flower Power",
      "Spinarak Attack",
      "Snubbull Snobbery",
      "The Little Big Horn",
      "The Chikorita Rescue",
      "Once in a Blue Moon",
      "The Whistle Stop",
      "Ignorance Is Blissey",
      "A Bout With Sprout",
      "Fighting Flyer With Fire",
      "For Crying Out Loud",
      "Tanks a Lot!",
      "Charizard's Burning Ambitions",
      "Grin to Win!",
      "Chikorita's Big Upset",
      "Foul Weather Friends",
      "The Superhero Secret",
      "Mild 'n Wooly",
      "Wired for Battle!",
      "Good 'Quil Hunting",
      "A Shadow of a Drought",
      "Going Apricorn!",
      "Gettin' the Bugs Out",
      "A Farfetch'd Tale",
      "Tricks of the Trade",
      "The Fire-ing Squad!",
      "No Big Woop!",
      "Tunnel Vision",
      "The Totodile Duel",
      "Hot Matches!",
      "Love, Totodile Style",
      "Fowl Play!",
      "Forest Grumps",
      "The Psychic Sidekicks!",
      "The Fortune Hunters",
      "A Goldenrod Opportunity"
    ]
  },
  {
    season: 4,
    name: "Johto League Champions",
    episodes: [
      "A Goldenrod Opportunity",
      "A Dairy Tale Ending",
      "Air Time",
      "The Bug Stops Here",
      "Type Casting",
      "Fossil Fools",
      "A Hot Water Battle",
      "Hook, Line and Stinker",
      "Beauty and the Breeder",
      "A Better Pill to Swallow",
      "Power Play",
      "Mountain Time",
      "Wobbu-Palooza!",
      "Imitation Confrontation",
      "The Trouble With Snubbull",
      "Ariados, Amigos",
      "Wings 'N' Things",
      "The Grass Route",
      "The Apple Corp!",
      "Houndoom's Special Delivery",
      "A Ghost of a Chance",
      "From Ghost to Ghost",
      "Trouble's Brewing",
      "All That Glitters!",
      "The Light Fantastic",
      "UnBEARable",
      "Moving Pictures",
      "Spring Fever",
      "Freeze Frame",
      "The Stolen Stones",
      "The Dunsparce Deception",
      "The Wayward Wobbuffet",
      "Sick Daze",
      "Ring Masters",
      "The Poké Spokesperson",
      "Control Freak",
      "The Art of Pokémon",
      "The Heartbreak of Brock",
      "Current Events",
      "Turning Over a New Bayleef",
      "Doin' What Comes Natu-rally",
      "The Big Balloon Blow-Up",
      "The Screen Actor's Guilt",
      "Right on, Rhydon!",
      "The Kecleon Caper",
      "The Joy of Water Pokémon",
      "Got Miltank?",
      "Fight for the Light",
      "Machoke, Machoke Man!",
      "The Perfect Match!"
    ]
  },
  {
    season: 5,
    name: "Master Quest",
    episodes: [
      "Around the Whirlpool",
      "Fly Me to the Moon",
      "Takin' It on the Chinchou",
      "A Corsola Caper!",
      "Mantine Overboard!",
      "Octillery the Outcast",
      "Dueling Heroes",
      "The Perfect Match!",
      "Plant It Now... Diglett Later",
      "Hi Ho Silver... Away!",
      "The Mystery is History",
      "A Parent Trapped!",
      "A Promise is a Promise",
      "Throwing in the Noctowl",
      "Nerves of Steelix!",
      "Bulbasaur... the Ambassador!",
      "Espeon, Not Included",
      "For Ho-Oh the Bells Toll!",
      "Extreme Pokémon!",
      "An EGG-sighting Adventure!",
      "Hatching a Plan",
      "Dues and Don'ts",
      "Just Waiting On a Friend",
      "A Tyrogue Full of Trouble",
      "Xatu the Future",
      "Talkin' 'Bout an Evolution",
      "Rage of Innocence",
      "As Cold as Pryce",
      "Nice Pryce, Baby!",
      "Whichever Way the Wind Blows",
      "Some Like it Hot!",
      "Hocus Pokémon",
      "As Clear as Crystal",
      "Same Old Song and Dance",
      "Enlighten Up!",
      "Will the Real Oak Please Stand Up?",
      "Wish Upon a Star Shape",
      "Outrageous Fortunes",
      "One Trick Phony!",
      "I Politoed Ya So!",
      "The Ice Cave!",
      "Beauty is Skin Deep",
      "Fangs for Nothin'",
      "Great Bowls of Fire!",
      "Better Eight Than Never",
      "Why? Wynaut!",
      "Just Add Water",
      "Lapras of Luxury",
      "Hatch Me if You Can",
      "Entei at Your Own Risk",
      "A Crowning Achievement",
      "Here's Lookin' at You, Elekid!",
      "You're a Star, Larvitar!",
      "Address Unown!",
      "Mother of All Battles",
      "Pop Goes the Sneasel",
      "A Claim to Flame!",
      "Love, Pokémon Style",
      "Tie One On!",
      "The Ties That Bind",
      "Can't Beat the Heat!",
      "Playing with Fire!",
      "Johto Photo Finish",
      "Gotta Catch Ya Later!",
      "Hoenn Alone!"
    ]
  },
  {
    season: 6,
    name: "Advanced",
    episodes: [
      "Get the Show on the Road!",
      "A Ruin with a View",
      "There's No Place Like Hoenn",
      "You Can Never Taillow",
      "In the Knicker of Time!",
      "A Poached Ego!",
      "Tree's a Crowd",
      "A Tail with a Twist",
      "Taming of the Shroomish",
      "You Said a Mouthful!",
      "A Bite to Remember",
      "The Lotad Lowdown",
      "All Things Bright and Beautifly!",
      "All in a Day's Wurmple",
      "Gonna Rule the School!",
      "The Winner by a Nosepass",
      "Stairway to Devon",
      "On a Wingull and a Prayer!",
      "Sharpedo Attack!",
      "Brave the Wave",
      "Which Wurmple's Which?",
      "A Hole Lotta Trouble",
      "Gone Corphishin'",
      "A Corphish Out of Water",
      "A Mudkip Mission",
      "Turning Over a New Nuzleaf",
      "A Three Team Scheme!",
      "Seeing is Believing!",
      "Ready, Willing, and Sableye",
      "A Meditite Fight!",
      "Just One of the Geysers",
      "Abandon Ship!",
      "Now That's Flower Power!",
      "Having a Wailord of a Time",
      "Win, Lose or Drew!",
      "The Spheal of Approval",
      "Jump for Joy!",
      "A Different Kind of Misty!",
      "A Poké-BLOCK Party!",
      "Watt's with Wattson?"
    ]
  },
  {
    season: 7,
    name: "Advanced Challenge",
    episodes: [
      "What You Seed is What You Get",
      "Love at First Flight",
      "Let Bagons Be Bagons",
      "The Princess and the Togepi",
      "A Togepi Mirage!",
      "Candid Camerupt!",
      "I Feel Skitty!",
      "Zig Zag Zangoose!",
      "Maxxed Out!",
      "Pros and Con Artists",
      "Come What May!",
      "Cheer Pressure",
      "Game Winning Assist",
      "Fight for the Meteorite!",
      "Poetry Commotion!",
      "Going, Going, Yawn",
      "Going for a Spinda",
      "All Torkoal, No Play",
      "Manectric Charge",
      "Delcatty Got Your Tongue",
      "Disaster of Disguise",
      "Disguise Da Limit",
      "Take the Lombre Home",
      "True Blue Swablu",
      "Gulpin it Down",
      "Exploud and Clear",
      "Go, Go Ludicolo!",
      "A Double Dilemma",
      "Love, Petalburg Style!",
      "Balance of Power!",
      "A Six-Pack Attack!",
      "The Bicker the Better",
      "Grass Hysteria!",
      "Hokey PokéBalls",
      "Whiscash and Ash",
      "Me, Myself and Time",
      "A Fan with a Plan",
      "Cruisin' for a Losin'",
      "Pearls are a Spoink's Best Friend",
      "That's Just Swellow",
      "Take This House and Shuppet!",
      "A Shroomish Skirmish",
      "Unfair Weather Friends",
      "Who's Flying Now?",
      "Sky High Gym Battle!",
      "Lights, Camerupt, Action!",
      "Crazy as a Lunatone",
      "The Garden of Eatin'",
      "A Scare to Remember",
      "Pokéblock, Stock, and Berry",
      "Lessons in Lilycove",
      "Judgment Day!"
    ]
  },
  {
    season: 8,
    name: "Advanced Battle",
    episodes: [
      "Clamperl of Wisdom",
      "The Relicanth Really Can!",
      "The Evolutionary War",
      "Training Wrecks",
      "Gaining Groudon",
      "The Scuffle of Legends",
      "It's Still Rocket Roll to Me!",
      "Solid as a Solrock",
      "Vanity Affair",
      "Where's Armaldo?",
      "A Cacturne for the Worse",
      "Claydol Big and Tall",
      "Once in a Mawile",
      "Beg, Burrow and Steal",
      "Absol-ute Disaster!",
      "Let It Snow, Let It Snow, Let It Snorunt!",
      "Do I Hear a Ralts?",
      "The Great Eight Fate!",
      "Eight Ain't Enough",
      "Showdown at Linoone",
      "Who, What, When, Where, Wynaut?",
      "Date Expectations",
      "Mean With Envy!",
      "Pacifidlog Jam",
      "Berry, Berry Interesting!",
      "Less is Morrison",
      "The Ribbon Cup Caper!",
      "Hi Ho Silver Wind!",
      "Deceit and Assist",
      "Rhapsody in Drew",
      "Island Time",
      "Like a Meowth to a Flame",
      "Saved by the Beldum",
      "From Brags to Riches",
      "Shocks and Bonds",
      "A Judgment Brawl",
      "Choose It or Lose It!",
      "At the End of the Fray",
      "The Scheme Team",
      "The Right Place at the Right Mime",
      "A Real Cleffa-hanger",
      "Numero Uno Articuno",
      "The Symbol Life",
      "Hooked on Onix",
      "Rough, Tough Jigglypuff",
      "On Cloud Arcanine",
      "Sitting Psyduck",
      "Hail to the Chef!",
      "Caterpie's Big Dilemma",
      "The Saffron Con",
      "A Hurdle for Squirtle",
      "Pasta La Vista!"
    ]
  },
  {
    season: 9,
    name: "Battle Frontier",
    episodes: [
      "Fear Factor Phony!",
      "Sweet Baby James",
      "A Chip Off the Old Brock",
      "Wheel of Frontier",
      "May's Egg-Cellent Adventure",
      "Weekend Warrior",
      "On Olden Pond",
      "Tactics Theatrics!",
      "Reversing the Charges",
      "The Green Guardian",
      "From Cradle to Save!",
      "Time-Warp Heals All Wounds",
      "Queen of the Serpentine!",
      "Off the Unbeaten Path",
      "Harley Rides Again",
      "Odd Pokémon Out!",
      "Spontaneous Combusken!",
      "Cutting the Ties That Bind!",
      "Ka Boom with a View!",
      "King and Queen for a Day!",
      "Curbing the Crimson Tide!",
      "What I Did for Love!",
      "Three Jynx and a Baby",
      "Talking a Good Game!",
      "Second Time's the Charm!",
      "All That Glitters is Not Golden!",
      "New Plot, Odd Lot!",
      "Going for Choke!",
      "The Ole' Berate and Switch",
      "Grating Spaces",
      "Battling the Enemy Within!",
      "Slaking Kong",
      "May, We Harley Drew'd Ya!",
      "Thinning the Hoard!",
      "Channeling the Battle Zone",
      "Aipom and Circumstance!",
      "Strategy Tomorrow – Comedy Tonight!",
      "Duels of the Jungle",
      "Overjoyed!",
      "The Unbeatable Lightness of Seeing!",
      "Pinch Healing!",
      "Gathering the Gang of Four!",
      "Pace – The Final Frontier!",
      "Once More with Reeling",
      "Home is Where the Start Is!"
    ]
  },
  {
    season: 10,
    name: "Diamond and Pearl",
    episodes: [
      "Following a Maiden's Voyage!",
      "Two Degrees of Separation!",
      "When Pokémon Worlds Collide!",
      "Dawn of a New Era!",
      "Gettin' Twiggy With It!",
      "Different Strokes for Different Blokes!",
      "Like It or Lup It!",
      "Gymbaliar!",
      "Setting the World on its Buneary!",
      "Not on My Watch Ya Don't!",
      "Mounting a Coordinator Assault!",
      "Arrival of a Rival!",
      "A Staravia is Born!",
      "Leave It to Brocko!",
      "Shapes of Things to Come!",
      "A Gruff Act to Follow!",
      "Wild in the Streets!",
      "O'er the Rampardos We Watched!",
      "Twice Smitten, Once Shy!",
      "Mutiny in the Bounty!",
      "Steamboat Willies",
      "Top-Down Training",
      "A Stand-Up Sit-Down!",
      "The Electrike Company!",
      "Malice in Wonderland!",
      "Mass Hip-Po-Sis!",
      "Ill-Will Hunting!",
      "A Maze-ing Race!",
      "Sandshrew's Locker!",
      "Satoshi and Hikari! Head for a New Adventure!!",
      "Dawn's Early Night!",
      "Tag! We're It...!",
      "Glory Blaze!",
      "Smells Like Team Spirit!",
      "Tears For Fears!",
      "Once There Were Greenfields",
      "Throwing the Track Switch",
      "The Grass-Type is Always Greener!",
      "An Angry Combeenation!",
      "All Dressed Up with Somewhere to Go!",
      "Buizel Your Way Out of This!",
      "An Elite Meet and Greet!",
      "A Secret Sphere of Influence!",
      "The Grass Menagerie!",
      "One Big Happiny Family!",
      "The Bells Are Ringing!",
      "Strategy with a Smile!",
      "Pikachu's Ghostly Journey",
      "Cooking Up a Sweet Story",
      "Oh Do You Know the Poffin Plan?",
      "Getting the Pre-Contest Titters!",
      "Settling a Not-So-Old Score!"
    ]
  }
];
